project:
  type: website
  output-dir: docs

website:
  title: "Alchemy Performance Institute"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Alchemy Archive/Physiology/physiology index.qmd
        text: Physiology


bibliography: /Users/nathanielyomogida/Documents/GitHub/Alchemy Performance Institute/Alchemy-Performance-Institute/Alchemy Archive/Bibliography/NGY CAK JVC Bibliography.bib
csl: /Users/nathanielyomogida/Documents/GitHub/Alchemy Performance Institute/Alchemy-Performance-Institute/Alchemy Archive/Bibliography/american-medical-association.csl

format:
  html:
    toc: true
    number-sections: true
    theme:
      light: cosmo
      dark: darkly
    mainfont: helvetica
    css: styles.css
  pdf: default

