project:
  type: website
  output-dir: docs

filters:
   - lightbox

author:
- id: NGY
  number: 1
  name: 
    given: Nathaniel 
    family:  Yomogida, SPT
    dropping-particle: Giovanni
  custom_title: SPT
- id: CAK
  number: 2
  name: 
    given: Chloë
    family:  Kerstein, SPT
    dropping-particle: Anne
  custom_title: SPT


website:
  page-navigation: true
  title: "Yomogida & Kerstein Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Alchemy Archive/archive_index.qmd
        text: Archive
      - href: guide.qmd
        text: Guide
      - href: journal club index.qmd
        text: Journal Club


bibliography: Alchemy Archive/Bibliography/NGY CAK JVC Bibliography.bib
csl: Alchemy Archive/Bibliography/american-medical-association.csl

format:
  html:
    toc: true
    toc-title: Contents
    number-sections: true
    tbl-cap-location: top
    theme:
      light: cosmo
      dark: darkly
    mainfont: helvetica
    css: styles.css
  pdf:
    toc: true
    number-sections: true
    link-citations: true
    link-bibliography: true
    

